# Generated by Django 3.2.8 on 2022-03-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=180)),
                ('alamat', models.DateTimeField(auto_now_add=True)),
                ('npm', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
