# Generated by Django 3.2.8 on 2022-03-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='alamat',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='nama',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='npm',
            field=models.CharField(max_length=40),
        ),
    ]
